apiVersion: v1
kind: Secret
metadata:
  name: {{ include "styra-local-plane.fullname" . }}-styra-credentials
  namespace: {{ .Values.namespace }}
  labels:
    {{- include "styra-local-plane.labels" . | nindent 4 }}
type: Opaque
stringData:
  slp.yaml: |
    discovery:
      name: discovery
      prefix: /systems/{{ .Values.systemId }}
      service: styra
    labels:
      system-id: {{ .Values.systemId }}
      system-type: template.istio:1.0
    services:
    - credentials:
        bearer:
          token: {{ .Values.bearerToken }}
      name: styra
      url: https://{{ .Values.tenant }}.styra.com/v1
    - credentials:
        bearer:
          token:  {{ .Values.bearerToken }}
      name: styra-bundles
      url: https://{{ .Values.tenant }}.styra.com/v1/bundles
